"""
The import sample files in samples/imports/, driven through the real HTTP
surface the Import page uses: /imports/preview -> /imports/map ->
/imports/validate -> /imports/commit.

Two jobs:
  1. prove the samples are honest — a new user who uploads them gets exactly
     the result README.md promises, not a surprise;
  2. keep them honest — if the importer's parsers, aliases or validation
     change, these assertions fail instead of the sample files silently
     becoming misleading.

The samples are generated by samples/imports/make_fixtures.py.
"""
from __future__ import annotations

import json
import pathlib

import pytest

FIXTURES = pathlib.Path(__file__).resolve().parents[2] / "samples" / "imports"


def _read(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


async def preview(api, name: str) -> dict:
    r = await api.client.post("/imports/preview", files={"file": (name, _read(name))})
    assert r.status_code == 200, r.text
    return r.json()


async def suggested_mapping(api, entity: str, name: str) -> dict:
    """Ask /imports/map, exactly as the UI does, and keep what it matched."""
    p = await preview(api, name)
    r = await api.client.post(
        "/imports/map",
        json={"entity": entity, "headers": p["columns"], "sample_rows": p["sample_rows"]},
    )
    assert r.status_code == 200, r.text
    return {m["column"]: m["field"] for m in r.json()["mappings"] if m["field"]}


async def validate(api, name: str, entity: str, mapping: dict) -> dict:
    r = await api.client.post(
        "/imports/validate",
        files={"file": (name, _read(name))},
        data={"entity": entity, "mapping": json.dumps(mapping)},
    )
    assert r.status_code == 200, r.text
    return r.json()


async def commit(api, name: str, entity: str, mapping: dict) -> dict:
    r = await api.client.post(
        "/imports/commit",
        files={"file": (name, _read(name))},
        data={"entity": entity, "mapping": json.dumps(mapping)},
    )
    assert r.status_code == 200, r.text
    return r.json()


async def import_file(api, name: str, entity: str) -> dict:
    """The full happy path for one sample file."""
    mapping = await suggested_mapping(api, entity, name)
    return await commit(api, name, entity, mapping)


# ---------------------------------------------------------------------------
# Detection: each file has to be recognised as what it is
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "name,entity",
    [
        ("products-clean.csv", "products"),
        ("products-messy-export.csv", "products"),
        ("products.xlsx", "products"),
        ("customers-clean.csv", "customers"),
        ("customers-storefront-export.csv", "customers"),
        ("orders-clean.csv", "orders"),
        ("orders-accounting-export.csv", "orders"),
    ],
)
async def test_the_dataset_is_detected_from_headers_and_samples(api, name, entity):
    p = await preview(api, name)
    assert p["entity"] == entity
    assert p["entity_confidence"] > 0.4, p
    assert p["row_count"] > 0


async def test_delimiters_are_sniffed(api):
    # A wrong delimiter guess would collapse each row into one column, so
    # asserting the full header list is the real check.
    messy = await preview(api, "products-messy-export.csv")
    assert messy["columns"] == [
        "Item Name", "Item Code", "Details", "Product Category",
        "Selling Price", "Cost Price", "Qty On Hand", "Reorder Point",
    ]
    accounting = await preview(api, "orders-accounting-export.csv")
    assert accounting["columns"] == [
        "Invoice #", "Date", "Customer", "Item", "Qty", "Rate", "Amount",
    ]
    assert (await preview(api, "products.xlsx"))["fmt"] == "xlsx"


async def test_an_unsupported_extension_is_refused_before_parsing(api):
    r = await api.client.post(
        "/imports/preview", files={"file": ("notes.pdf", _read("products-clean.csv"))}
    )
    assert r.status_code == 400
    assert "Unsupported file type" in r.json()["detail"]


# ---------------------------------------------------------------------------
# The clean files import completely
# ---------------------------------------------------------------------------

async def test_products_clean(api):
    p = await preview(api, "products-clean.csv")
    assert p["row_count"] == 12
    mapping = await suggested_mapping(api, "products", "products-clean.csv")
    v = await validate(api, "products-clean.csv", "products", mapping)
    assert v["valid_rows"] == 12
    assert v["errors"] == []
    assert v["would_create"]["products"] == 12

    out = await import_file(api, "products-clean.csv", "products")
    assert out["created"]["products"] == 12
    assert out["skipped"] == {"existing": 0, "in_file": 0, "errors": 0}
    assert out["errors"] == []


async def test_customers_clean(api):
    out = await import_file(api, "customers-clean.csv", "customers")
    assert out["created"]["customers"] == 10
    assert out["errors"] == []


async def test_orders_clean_after_products_and_customers(api):
    # The realistic order: catalogue and people first, then sales history.
    products = await import_file(api, "products-clean.csv", "products")
    assert products["created"]["products"] == 12
    customers = await import_file(api, "customers-clean.csv", "customers")
    assert customers["created"]["customers"] == 10

    v = await validate(
        api, "orders-clean.csv", "orders",
        await suggested_mapping(api, "orders", "orders-clean.csv"),
    )
    assert v["valid_rows"] == 18
    assert v["errors"] == []
    assert v["unknown_refs"] == {"customers": 0, "products": 0}

    out = await import_file(api, "orders-clean.csv", "orders")
    assert out["created"]["orders"] == 18
    assert out["created"]["order_items"] == 18
    assert out["errors"] == []


async def test_reimporting_the_same_files_creates_nothing_twice(api):
    await import_file(api, "products-clean.csv", "products")
    await import_file(api, "customers-clean.csv", "customers")
    await import_file(api, "orders-clean.csv", "orders")

    again_products = await import_file(api, "products-clean.csv", "products")
    assert again_products["created"]["products"] == 0
    assert again_products["skipped"]["existing"] == 12

    again_orders = await import_file(api, "orders-clean.csv", "orders")
    assert again_orders["created"]["orders"] == 0
    assert again_orders["skipped"]["existing"] == 18


# ---------------------------------------------------------------------------
# The messy real-world exports: aliases, currency signs, no email column
# ---------------------------------------------------------------------------

async def test_messy_export_maps_by_alias_and_parses_naira(api):
    mapping = await suggested_mapping(api, "products", "products-messy-export.csv")
    # "Item Name" / "Selling Price" / "Qty On Hand" / "Reorder Point" are not
    # Co-op field names; the mapper has to land them anyway.
    assert mapping["Item Name"] == "name"
    assert mapping["Selling Price"] == "unit_price"
    assert mapping["Cost Price"] == "cost_price"
    assert mapping["Qty On Hand"] == "current_stock"
    assert mapping["Reorder Point"] == "reorder_level"

    out = await commit(api, "products-messy-export.csv", "products", mapping)
    assert out["created"]["products"] == 8
    assert out["errors"] == []

    products = (await api.client.get("/products", params={"limit": 100})).json()["items"]
    yam = next(p for p in products if p["name"] == "Yam tuber (large)")
    assert yam["unit_price"] == 4500.0, "₦4,500.00 must parse to 4500"
    assert yam["current_stock"] == 120


async def test_storefront_customers_without_email_get_a_placeholder(api):
    out = await import_file(api, "customers-storefront-export.csv", "customers")
    assert out["created"]["customers"] == 8

    customers = (await api.client.get("/customers", params={"limit": 100})).json()["items"]
    emails = [c["email"] for c in customers]
    assert all(emails), "every customer must end up with a usable email"
    assert len(set(emails)) == len(emails), "placeholders must not collide"
    generated = next(c for c in customers if c["full_name"] == "Ibrahim Danladi")
    assert "ibrahim" in generated["email"].lower()


async def test_accounting_export_without_an_email_column(api):
    await import_file(api, "products-clean.csv", "products")
    await import_file(api, "customers-clean.csv", "customers")

    mapping = await suggested_mapping(api, "orders", "orders-accounting-export.csv")
    assert mapping["Invoice #"] == "order_id"
    assert mapping["Date"] == "order_date"
    assert mapping["Customer"] == "customer_name"
    assert mapping["Item"] == "product_name"
    assert mapping["Qty"] == "quantity"
    assert mapping["Rate"] == "unit_price"

    out = await commit(api, "orders-accounting-export.csv", "orders", mapping)
    assert out["created"]["orders"] == 12
    assert out["errors"] == []


async def test_xlsx_products(api):
    out = await import_file(api, "products.xlsx", "products")
    assert out["created"]["products"] == 6
    assert out["errors"] == []


# ---------------------------------------------------------------------------
# The broken files: every bad row is named, the good rows still land
# ---------------------------------------------------------------------------

async def test_products_with_errors_names_every_bad_row(api):
    mapping = await suggested_mapping(api, "products", "products-with-errors.csv")
    v = await validate(api, "products-with-errors.csv", "products", mapping)

    assert v["total_rows"] == 11
    assert v["valid_rows"] == 7
    assert len(v["errors"]) == 4
    assert v["duplicates"]["in_file"] == 1
    assert v["would_create"]["products"] == 6
    # The report has to say which rows failed, by row number.
    assert [e["row"] for e in v["errors"]] == [8, 9, 10, 11]

    out = await commit(api, "products-with-errors.csv", "products", mapping)
    assert out["created"]["products"] == 6
    assert out["skipped"]["errors"] == 4
    assert out["skipped"]["in_file"] == 1
    assert len(out["errors"]) == 4


async def test_orders_with_errors_reports_the_unknown_customer(api):
    await import_file(api, "products-clean.csv", "products")
    await import_file(api, "customers-clean.csv", "customers")

    mapping = await suggested_mapping(api, "orders", "orders-with-errors.csv")
    v = await validate(api, "orders-with-errors.csv", "orders", mapping)
    assert v["total_rows"] == 8
    assert len(v["errors"]) == 4, [e["detail"] for e in v["errors"]]
    assert v["unknown_refs"], "the ghost customer must be reported before commit"

    out = await commit(api, "orders-with-errors.csv", "orders", mapping)
    assert out["created"]["orders"] == 3
    assert out["skipped"]["errors"] == 5
    details = " ".join(e["detail"] for e in out["errors"])
    assert "ghost@example.com" in details
    assert "quantity must be at least 1" in details


# ---------------------------------------------------------------------------
# The imported history has to be usable, not just stored
# ---------------------------------------------------------------------------

async def test_imported_history_feeds_the_reports(api):
    await import_file(api, "products-clean.csv", "products")
    await import_file(api, "customers-clean.csv", "customers")
    await import_file(api, "orders-clean.csv", "orders")

    sales = await api.client.get(
        "/reports/sales", params={"from": "2026-01-01", "to": "2026-12-31"}
    )
    assert sales.status_code == 200, sales.text
    kpis = {k["key"]: k["value"] for k in sales.json()["kpis"]}
    assert kpis["revenue"] > 0
    assert kpis["orders"] == 18
    # Totals straight off the sample file: 222 units, ₦3,603,300 across 18 lines.
    assert kpis["units"] == 222
    assert kpis["revenue"] == 3603300
